[[lattices]]
title = "BESSY 3 Design Kuske 5BA 20p Reference"
authors = ["Bettina Kuske"]
namespace = "kuske"
machine = "bessy3"
name = "bessy3_5ba-20p_v_reference"
energy = 2500
simulations = ["elegant", "madx", "apace"]
description = """
Referenzlösung (kleines alpha)
"""

[[lattices]]
title = "BESSY 3 Design Kuske 5BA 20p Long Bend TGRB"
authors = ["Bettina Kuske"]
namespace = "kuske"
name = "b3_5ba-20p_v_long-bend-tgrb"
energy = 2500
simulations = ["elegant"]
labels = ["antibends", "combined function bends"]
description = """
5bend MBA lattice, 20 Perioden, langer Dipol mit transversem Gradienten und Gradienten 
im reverse bend, sprich versetzter Quadrupol
"""

[[lattices]]
title = "BESSY 3 Design Hwang 4 Sexts"
authors = ["Ji-Gwang Hwang"]
namespace = "hwang"
name = "bessy3_4sexts_v_1"
energy = 2500
labels = ["combined function bends"]
simulations = ["elegant", "madx"]
description = """
"""

[[lattices]]
title = "BESSY 3 Design Hwang 5 Sexts"
authors = ["Ji-Gwang Hwang"]
namespace = "hwang"
name = "bessy3_5sexts_v_1"
energy = 2500
simulations = ["elegant", "madx"]
labels = ["combined function bends"]
description = """
"""

[[lattices]]
title = "BESSY II Standard User 2019"
authors = ["HZB"]
namespace = "andreas"
name = "bessy2_stduser-2019-05-07-v_1"
energy = 1700
simulations = ["apace"]
description = """
Standard User lattice of the BESSY II storage ring
(Here as reference and to test stuff!)
"""


[[lattices]]
title = "BESSY II Design Lattice 1996"
author = ["HZB"]
namespace = "andreas"
name = "bessy2_design-1996_v_1"
energy = 1700
simulations = ["apace"]
description = """
Fully symmetric Design Lattice of the BESSY II storage ring
(Here as reference and to test stuff!)
"""
